name: Build APK
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git python3 python3-dev python3-venv wget
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        sudo apt-get install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
        sudo apt-get install -y libgstreamer1.0-dev
        sudo apt-get install -y libgstreamer-plugins-base1.0-dev
        sudo apt-get install -y libpango1.0-dev libgl1-mesa-dev libgles2-mesa-dev
        sudo apt-get install -y xclip xsel libjpeg-dev

    - name: Install buildozer requirements
      run: |
        sudo apt-get install -y build-essential zlib1g-dev python3 python3-dev python3-pip python3-virtualenv
        sudo apt-get install -y cmake pkg-config
        sudo apt-get install -y libfreetype6-dev libgl1-mesa-dev libgles2-mesa-dev
        sudo apt-get install -y libgstreamer1.0-dev gstreamer1.0-plugins-{bad,base,good,ugly}
        sudo apt-get install -y gstreamer1.0-{omx,alsa} libmtdev-dev
        sudo apt-get install -y libpango1.0-dev libpangoft2-1.0-0 openssl
        sudo apt-get install -y autoconf automake libtool
        sudo apt-get install -y build-essential ccache git libncurses5:i386 libstdc++6:i386 libgtk2.0-0:i386 
        sudo apt-get install -y libpangox-1.0-0 libpangoxft-1.0-0 libidn11:i386 python2.7 python2.7-dev 
        sudo apt-get install -y openjdk-11-jdk unzip zlib1g-dev zlib1g:i386

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: bin/*.apk
