name: Build APK
on: workflow_dispatch  # 只保留手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0-dev \
          gstreamer1.0-plugins-{bad,base,good,ugly} \
          gstreamer1.0-tools \
          libpango1.0-dev \
          libgl1-mesa-dev \
          zip \
          unzip \
          openjdk-11-jdk

    - name: Setup Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install Cython==0.29.33
        pip install buildozer==1.5.0
        pip install kivy==2.1.0 pillow plyer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: bin/*.apk
        if-no-files-found: error
