name: Build APK
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0-dev \
          gstreamer1.0-plugins-{bad,base,good,ugly} \
          gstreamer1.0-tools \
          libpango1.0-dev \
          libgl1-mesa-dev \
          zip \
          unzip \
          openjdk-11-jdk \
          autoconf \
          automake \
          libtool \
          libltdl-dev \
          libffi-dev \
          pkg-config

    - name: Setup Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install Cython==0.29.33
        pip install buildozer
        # 安装应用程序依赖
        pip install kivy pillow plyer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: bin/*.apk
        if-no-files-found: error
