name: Build APK
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Cache Buildozer deps
      uses: actions/cache@v3
      with:
        path: .buildozer_cache
        key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
        sudo apt-get install -y libgstreamer1.0-dev gstreamer1.0-plugins-{bad,base,good,ugly} gstreamer1.0-tools libpango1.0-dev libgl1-mesa-dev libgles2-mesa-dev
        sudo apt-get install -y xclip xsel libjpeg-dev pkg-config libpango1.0-dev libgles2-mesa-dev build-essential python-is-python3
        sudo apt-get install -y libgl1 libgles2 ccache git openjdk-11-jdk autoconf automake libtool libltdl-dev libffi-dev

    - name: Install buildozer
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade Cython==0.29.33 buildozer
        # 安装其他 Python 依赖
        pip install kivy pillow requests

    - name: Build APK
      run: |
        # 更新 PATH 以包含 ~/.local/bin
        export PATH=$PATH:~/.local/bin
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: bin/*.apk
        if-no-files-found: error
